### ISSUE TITLE
client.py

### ISSUE THREAD

**Issue by fdrouhin-uha** [dragbee/R309#1]
Bonjour,
J'ai trouvé le code client pour un autre étudiant. Est-ce bien normal ?
Bonne fin de journée,
Frédéric

**Comment by dragbee** [comment]
Bonjour, j'ai repris le code que M.Albert a envoyé sur discord. Je ne comprends pas

**Comment by fdrouhin-uha** [comment]
> Bonjour, j'ai repris le code que M.Albert a envoyé sur discord. Je ne comprends pas

Bonjour, d'accord, alors vous êtes plusieurs étudiants à l'avoir fait. Merci pour l'explication.
